import { compiler } from './dist/index.module.js'
const input = `1. "Jahody - přírodní sladkost pro zdravý život"
2. "Sázíme jen na nejlepší jahody!"
3. "Jahodový ráj v každém košíku!"
4. "Chuť léta v každé jahodě"
5. "Neodolatelná sladkost Hello world"
6. "Jahody plné vitamínů"
7. "100% přírodní svěžest jahod"
8. "Krásně červené, neuvěřitelně chutné"
9. "Jahody pro každý den"
10. "Nezapomeňte - jahoda denně, doktor pryč z cesty!"
11. "Chuťový zážitek v každé jahodě"
12. "Svěžest a sladkost v jednom"
13. "Jahody - pamatujte na své zdraví"
14. "Náš výběr jahod je číslo jedna!"
15. "Příroda v každé jahodě"
16. "Malé jahody, velký význam"
17. "Jahody - čerstvé, zdravé, chutné"
18. "Jahody - pro radost ze života"
19. "Jahody - rajské potěšení"
20. "Vždy čerstvé, vždy skvělé"
21. "Vaše oblíbené jahody nás inspirovaly"
22. "Jahody - vaše každodenní mlsání"
23. "Skvělé jahody, skvělý výběr"
24. "Pro ty, kteří milují jahody"
25. "Jahody - pro sladký život"
26. "Jahody pro každou příležitost"
27. "Jahody - čerstvost, kterou milujete"
28. "Osvěžující jahody pro horké letní dny"
29. "Jahody, které vás nikdy nezklamou"
30. "Jahody - přírodní zázrak"
31. "Jahody - pro ty, kteří chtějí více"
32. "Vyberte si jahody, vyberte si zdraví"
33. "Jahoda - královna ovoce"
34. "Jahody - sladký poklad přírody"
35. "Jahody - pro zdravé mlsání"
36. "Jahody - pro lepší den"
37. "Zasloužíte si nejlepší jahody"
38. "Nejoblíbenější jahody v městě"
39. "Naše jahody, vaše radost"
40. "Jahody - chuť, kterou milujete"

- aaa
- bbb
- ccc`;
compiler(input)